version: '3.5'

services:

  mini-validator-list-backend:
    container_name: mini-validator-list-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: mini-validator-list-backend
    networks:
      - mini-validator-list
    volumes:
      - ./backend/build/src:/usr/src/api
    environment:
      NODE_ENV: development

  mini-validator-list-frontend:
    container_name: mini-validator-list-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: mini-validator-list-frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/dist
    networks:
      - mini-validator-list
    depends_on:
      - mini-validator-list-backend
    environment:
      NODE_ENV: development

networks:
  mini-validator-list: